### ISSUE TITLE
Feature Request - Allow wider Canvas grid for panels

### ISSUE THREAD

**Issue by khorton** [SCHibbard/enphase-dashboard#1]
Currently, the maximum Canvas grid allowed by anaphase-canvas.py is 15.  It would be useful if that could be larger.  In my case, I'd like to have a width of 17, so I can put my two roof sections side by side on the grid.  As it sits now, I need to offset them vertically, which uses enough vertical space that scrolling is required to see everything.  I'll edit MAX_WIDTH and redefine my grid

**Comment by SCHibbard** [comment]
Will add to list. Was a little worried about making it wider as a terminal window could max out, but if it's needed it's needed! Hopefully you did a 'save' when you first made it, probably easier to swap around panels than create again from scratch.

**Comment by khorton** [comment]
I had done a save, but I didn't initially discover all the edits needed to increase the allowable width. So I started over.  One mug of coffee later it is done and looking as I want.
