### ISSUE TITLE
Enphase data now only updates hourly (approx)

### ISSUE THREAD

**Issue by khorton** [SCHibbard/enphase-dashboard#14]
Everything had been working pretty much as expected until yesterday.  All data was updated every five minutes.  Starting yesterday, the dashboard only gets new data about every hour (typically at 47 minutes after the hour, but sometimes at 46, 48 or 49).  I upgraded to the latest versions of the Powerwall-Dashboard (v4.4.6) and to v0.6.0 of the Enphase-Dashboard.  I restarted the Powerwall-Dashboard, and restarted the server.  Nothing has helped.

It is almost like Enphase has remotely changed something in their system so that it only responds once per hour.  I logged into the Gateway, and it reports Envoy SW version: D7.3.621 (150e3e) with a build date of 13 Oct, 2023 1:39 PM

Any troubleshooting ideas would be greatly appreciated

**Comment by SCHibbard** [comment]
Had not noticed, but you are right - mine is doing the same.  Was updating every 5 minutes, when to updating once per hour starting somewhere overnight between 26 & 27 July.  I have the same gateway SW as you.  I just submitted a ticket to Enphase, let's see what they say.

Curious:  what version SW do your inverters have?  Mine are all v02.61.01

**Comment by khorton** [comment]
I'm glad it isn't something unique to me.  And hopefully this is maybe an Enphase error, and they will correct it, so nothing for us to do.

My inverters are all on v02.61.01 as well.

**Comment by khorton** [comment]
Any chance this is an issue with the v1 api being deprecated?  The info I can find on the Enphase site suggests they are moving to a v4 api, and even v2 is supposed deprecated.  https://developer-v4.enphase.com/aboutproduct.html

**Comment by SCHibbard** [comment]
As far as I understand, the V4 change was only for the Cloud API. enphase-dashboard only uses the local API, which hasn't changed. In fact I was using it for more than a year - with no issues - before posting the Enphase-dashboard repository. By the way, V4 is what also introduced the nasty pricing model, which screws getting missing history, but different problem!

However, could be that changes they made when they shut down v2 affected the local api.

No word yet from my service ticket at Enphase ...

**Comment by khorton** [comment]
Fingers crossed that this wasn't a delusional attempt to push people to the V4 API in order to boost revenue

**Comment by khorton** [comment]
Any word from Enphase on this?

**Comment by SCHibbard** [comment]
Yes, crappy graphs bugging the hell out of me too!  2 email exchanges with their regular customer service that both resulted in "contact API group". I did, no response.  I'll give it one more try, then I think it's time to shame them publicly.

**Comment by SCHibbard** [comment]
@khorton:
Got an Email overnight from Enphase that they had "set the reporting intervals back to default".  Sure enough, mine are back to 5-min. intervals this morning.  Let me know if you see same.

**Comment by khorton** [comment]
Progress!  I'm still at one hour intervals.  Perhaps they need to intervene manually for every user who complains.  Who should I contact to sort this out?  Thanks

**Comment by SCHibbard** [comment]
I was wondering the same (only updated mine and not whole network).  Also do not know how long it takes to propagate an update through their network if they update all, so you may see it yet.  Mine was at one hour intervals up until sunset last night, but started out at 5-min this AM.  I emailed api@enphaseenergy.com.

**Comment by SCHibbard** [comment]
Just looked at firmware versions.  My IQ Gateway firmware version did not change, it was D7.3.621 before and still is.  Not sure if the change is just a parameter setting, or is in the microinverter firmware, but I wasn't smart enough to note the microinverter firmware versions before.  They are now v02.61.01

**Comment by khorton** [comment]
My Gateway is still at D7.3.621 (150e3e).  I haven't figured out where to find inverter firmware.  I think I had stumbled across it weeks ago, but I don't seem to have taken any notes on where I found that info

**Comment by khorton** [comment]
And, I see from the earlier comments in this thread, that both our inverters were on v02.61.01 at the start of this saga

**Comment by khorton** [comment]
Bingo! Found the inverter firmware in the Enphase web app.  Still at v02.61.01

**Comment by SCHibbard** [comment]
Oops, should have looked here, forgot I recorded the inverters too.  So it is apparently a setting and not a FW change. I'd guess you're going to have to complain directly.

**Comment by khorton** [comment]
I sent them an email. If they are going to muck about with customer installations and screw them up, they should expect to get some complaints

**Comment by khorton** [comment]
They replied, apologizing for the inconvenience and set me back to the default interval.  I've got 5 minute updates again.

Thanks for chasing down the cause of this.  And thanks so much for sharing your work to get this data displayed in the first place.

**Comment by SCHibbard** [comment]
Boy, you rate, took 1 day short of a month for them to respond to me!  Yes, they we're cordial, I think the help desk is overloaded/understaffed.  Glad we're back to charts that don't look like a Cybertruck.  Not sure what could have caused this.  the fact they only seem to be correcting it for those that complain tells me it was most likely an intentional modification.  Why is the question. May never know.

Thanks for all YOUR help.  Glad to have a second pair of eyes look at the project - gave me good feedback on what needed improving/fixing.  I think the version up now is fairly stable.

**Comment by khorton** [comment]
I'm guessing the guy/gal who saw my message was already aware of your issue, so they knew right away exactly how to fix it.  It could have been a deliberate change, or an unexpected side effect of another change.  They probably rightly judge that most users won't notice this issue, so no need to roll it back for everyone.  

If this was a deliberate change, I cannot guess what the motivation was.  If I understand correctly, there should be no impact to Enphase of calls to the local API.   Those calls shouldn't hit their servers at all.  So why expend resources to bork the local API calls?  The only way that makes sense is if they hoped to introduce some sort of subscription service so the handful of users who cared could get higher frequency data.  But 99.9% of users don't care, so the potential income is peanuts.  Probably less than the cost of developing and maintaining the service.

**Comment by khorton** [comment]
I'm back to one hour reporting intervals again :(.  I'll contact Enphase API Support again.

**Comment by SCHibbard** [comment]
Thanks for alerting ... I see same starting this AM.  Will report as well. I see no changes in Gateway or Inverter FW versions (D7.3.621 & v02.61.01 respectively).

**Comment by khorton** [comment]
Yes, still on D7.3.621 & v02.61.01 here as well

**Comment by khorton** [comment]
And now I'm back to 5 minute update intervals again, as of about 15 minutes ago.

**Comment by SCHibbard** [comment]
I as well, starting about 7:30 Central.  I'm guessing they have parameter sets they download to gateways and/or inverters to optimize them, and it overwrites all parameters in the system. Hence FW not incrementing.  I asked if an account can be marked to lock the local API update frequency parameter.   Longshot, let's see ...

**Comment by khorton** [comment]
I made a similar request about locking changes to the local API.  Hopefully they are willing to change whatever process is screwing this up so that it no longer mucks up the local API update frequency.  If it is only affecting the two of us, they might judge it is easier to deal with the customer support requests than it is to revise whatever process is screwing up the local API

**Comment by SCHibbard** [comment]
Not sure if it is only the two of us. Since they published the docs on the local API, I have to imagine there are a number of people out there taking advantage of it!

**Comment by khorton** [comment]
Enphase API Support sent me the following in an email "I have checked with the software team and got the update that the reporting intervals will not be affected anymore. Please respond to this email in case the issue repeats"

I assume they sent the same to you, but I'm putting it here just in case they didn't

**Comment by SCHibbard** [comment]
They must like you!  I never got a notice.  Thanks for letting me know.

**Comment by khorton** [comment]
I think the data reporting interval has changed again for me.  Looks like each inverter is reporting every 15 minutes, but they are not all on the same reporting times.  It certainly isn't as bad as one hour, but a downgrade from the previous 5 minute intervals.  More observation required to confirm this.

**Comment by SCHibbard** [comment]
Mine too ... thanks for noticing. Looks to be 15 minutes. contacting...

**Comment by khorton** [comment]
I'm beating my head against the wall trying to figure out how to query influxdb to show my the recent panel data, so I can confirm what the interval for each panel is.  I can get into influxdb, but haven't figured out what query I need.  Any hints would be appreciated.

**Comment by khorton** [comment]
I just remembered that I had used INSPECT in Grafana before.  I found what I need to confirm that I'm getting 15 minute intervals

**Comment by SCHibbard** [comment]
Yes, inspect works, sorry I didn't catch you while you were still beating your head against the wall.  You can also click one of the solar panel numbers at the bottom of the Grafana panel, and all will disappear except that one (click it again to get them all back).  If you then zoom in on a short period of time (click somewhere in the graph, then drag), you can then follow along with your cursor and see the time points.  It's a bit faster than opening inspect and creating a query.

**Comment by khorton** [comment]
Thanks!  I had not noted that before

**Comment by SCHibbard** [comment]
They set it back to 5 minutes for me overnight.

**Comment by khorton** [comment]
I'm back to 5 min intervals as well.  The API support person who reset it said they would check with the SW team to attempt to get this to not happen in the future (I'm not at all hopeful)

**Comment by khorton** [comment]
I'm back to 15 minutes again.  Email sent to Enphase.

**Comment by SCHibbard** [comment]
Sigh, as well.

**Comment by khorton** [comment]
I might work on a script that runs 10 minutes after sunrise. If total Enphase production is zero - send email to Enphase asking them to reset the reporting interval

**Comment by khorton** [comment]
I'm back at 5 minute update interval, as of about 3 hours ago.  No email from Enphase

**Comment by SCHibbard** [comment]
I am back at 5 as well. Got a response that the help desk is trying to get a permanent solution worked out

**Comment by khorton** [comment]
I'm back to one hour intervals.  Grr!!

**Comment by khorton** [comment]
I'm starting to wonder if they have decided it is cheaper to spend the customer support time to reset us every week or two than it is to expend engineering resources to revise whatever automatic process keeps screwing it up

**Comment by SCHibbard** [comment]
Yup, me too.  6 days after last fix.

**Comment by khorton** [comment]
I'm back at 5 minute updating again.  No response to yesterday's email to Enphase API Support

**Comment by SCHibbard** [comment]
Same here

**Comment by khorton** [comment]
I've just noticed that the data went to 15 minute intervals during the morning of March 24, and has been at 15 minute intervals since.  I've been on vacation, so haven't been paying close attention to it until this evening.  I'll email my contact to shake their tree.

**Comment by khorton** [comment]
Enphase Support responded quickly, and I'm back to five minute intervals again.

**Comment by SCHibbard** [comment]
> Enphase Support responded quickly, and I'm back to five minute intervals again.

Hadn't been looking at mine closely lately, but just did and it also went back to 15. just emailed them. Guess 15 is still the standard and we ae the exception. Thanks for noticing.
