### ISSUE TITLE
Unchanging Minute Values in Solar Panel Production panel title

### ISSUE THREAD

**Issue by khorton** [SCHibbard/enphase-dashboard#3]
The Solar Panel Production panel has a title showing the start and end of the period shown.  On my machine, the minute values of both start and end are always "06".  This is true even if the chosen period is the last 30m or 15m.  Or if the period chosen is the current calendar day.

E.g. the chosen period is the calendar day 2024-06-22.  The title is "Solar Panel Production Between 2024-Jun-22 00:06 and 2024-Jun-22 23:06".  The displayed production values do change when the selected period changes, so this is only a very minor issue.

**Comment by SCHibbard** [comment]
Thanks for catching. It's using the 2-digit month number rather than minutes.  I'll fix when back. Grafana documentation for that kind of stuff is hard to find. Got that info from a discussion somewhere.

**Comment by khorton** [comment]
Oh...  So I need to switch it from "MM" to "mm" (or vice versa)

**Comment by khorton** [comment]
Switching the two instances of "MM" to "mm" fixed it.

**Comment by SCHibbard** [comment]
Thanks, assumed that would be it. Can't edit dashboards from Croatia, have it disabled externally.
